# 1. 文件路径
train_file_paths:
  satellite_path: "../data/train/himawari_nc/"
  crop_statellite_path: "../data/train/crop_himawari/"
  aligned_satellite_path: "../data/train/crop_himawari/15min"
  pv_file: "../data/筛选2020-2023数据.csv"
  series_file: "../data/train/series_file.csv"

val_file_paths:
  satellite_path: "../data/val/himawari_nc/"
  crop_statellite_path: "../data/val/crop_himawari/"
  aligned_satellite_path: "../data/val/crop_himawari/15min"
  pv_file: "../data/筛选2024数据.csv"
  series_file: "../data/val/series_file_test.csv"


scaler_params_paths: "../data/scaler_params.json"

pkg_path: "../checkpoints/"

# 2. 电站配置
train_stations:
  lat: -23.75
  lon: 133.85
  altitude: 545
  capacity: 5

val_stations:
  lat: -23.75
  lon: 133.85
  altitude: 545
  capacity: 5

# 3. 要处理的卫星图像
statellite:
  crop_size: 96  # 96x96 pixels

# 4. 要处理的时间
train_dates:
  start_date: "2021-08-19"
  end_date: "2021-09-08"

val_dates:
  start_date: "2024-01-01"
  end_date: "2024-12-31"

